/*
 * @Author: szx
 * @Date: 2021-07-04 19:00:58
 * @LastEditTime: 2023-04-08 12:17:36
 * @Description: 窗口的多语言支持
 * @FilePath: \push-markdown\packages\main\src\app-menu\menu-lang.ts
 */

'use strict';

export const en = {
  file: 'File',
  open: 'Open',
  openRecent: 'Open Recent',
  clearRecent: 'Clear',
  save: 'Save',
  publish: 'Publish',
  language: 'Language',
  settings: 'Settings',
  upload: 'Batch Upload',
  edit: 'Edit',
  undo: 'Undo',
  redo: 'Redo',
  cut: 'Cut',
  copy: 'Copy',
  paste: 'Paste',
  selectAll: 'Select All',
  reload: 'Reload',
  fileTree: 'File tree',
  closeTab: 'Close Current File',
  reloadFile: 'Reload File',
  toggleFullScreen: 'Toggle Full Screen',
  toggleDevTools: 'Toggle Developer Tools',
  window: 'Window',
  minimize: 'Minimize',
  close: 'Close',
  help: 'Help',
  learnMore: 'Learn More',
  checkUpdate: 'Check Update',
  openWelcomePage: 'Open Welcome Page',
  viewSampleFile: 'View Sample File',
  tutorials: 'Tutorials',
  about: 'About ',
  services: 'Services',
  hide: 'Hide ',
  hideOthers: 'Hide Others',
  showAll: 'Show All',
  quit: 'Quit',
  bringAllToFront: 'Bring All to Front',
  theme: 'Theme',
  light: 'Light',
  dark: 'Dark'
};

export const zh = {
  file: '文件',
  open: '打开',
  openRecent: '打开最近使用的',
  clearRecent: '清除',
  save: '保存',
  publish: '发布',
  language: '语言',
  settings: '设置',
  upload: '批量上传',
  edit: '编辑',
  undo: '撤销',
  redo: '重做',
  cut: '剪切',
  copy: '复制',
  paste: '粘贴',
  selectAll: '全选',
  reload: '重新加载',
  fileTree: '文件列表',
  closeTab: '关闭当前文件',
  reloadFile: '重新载入文件',
  toggleFullScreen: '切换全屏',
  toggleDevTools: '切换开发者工具',
  window: '窗口',
  minimize: '最小化',
  close: '关闭',
  help: '帮助',
  learnMore: '了解更多',
  checkUpdate: '检查更新',
  openWelcomePage: '打开欢迎页',
  viewSampleFile: '查看示例文档',
  tutorials: '使用教程',
  about: '关于',
  services: '服务',
  hide: '隐藏',
  hideOthers: '隐藏其他',
  showAll: '显示全部',
  quit: '退出',
  bringAllToFront: '前置全部窗口',
  theme: '主题',
  light: '浅色',
  dark: '深色'
};
